# Generated by Django 3.2.8 on 2021-10-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Poll`s name')),
                ('start_date', models.DateField(editable=False)),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
